# Generated by Django 4.2.6 on 2023-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course_course_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='job',
            new_name='profession',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='about',
            field=models.TextField(),
        ),
    ]
