# Generated by Django 4.2.6 on 2023-11-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_job_trainer_profession_alter_trainer_about'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school_info',
            table='school_info',
        ),
    ]
