# Generated by Django 4.2.6 on 2023-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_course_trainer_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.course'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
