# Generated by Django 4.2.6 on 2023-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_student_course_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='mainapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='mainapp.trainer'),
        ),
    ]
