# Generated by Django 4.2.6 on 2023-11-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_student_course_alter_student_trainers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
